services:
  blog-page:
    container_name: blog-page
    image: wwricu/blog-page:snapshot
    restart: always
    expose:
      - 3000
    environment:
      - NEXT_BASE_URL=http://basic-service:8000
      - NEXT_SITE_URL=https://${HOSTNAME}
    networks:
      - default_network
