services:
  caddy:
    container_name: caddy
    image: wwricu/admin-page:latest
    restart: always
    volumes:
      - /data/caddy/data:/data/caddy
      - /data/caddy/log:/var/log
    environment:
      - HOSTNAME=${HOSTNAME}
      - ADMIN_HOSTNAME=${ADMIN_HOSTNAME}
    ports:
      - "443:443"
      - "80:80"
    networks:
      - default_network
  basic-service:
    container_name: basic-service
    image: wwricu/basic-service:latest
    restart: on-failure:3
    expose:
      - 8000
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - /data/basic-service:/data
    networks:
      - default_network
  blog-page:
    container_name: blog-page
    image: wwricu/blog-page:latest
    restart: always
    expose:
      - 3000
    environment:
      - NEXT_BASE_URL=http://basic-service:8000
    networks:
      - default_network
  v2ray:
    container_name: v2ray
    image: v2fly/v2fly-core:latest
    restart: always
    expose:
      - 8443
    volumes:
      - /data/deploy/v2ray/config.json:/etc/v2ray/config.json
      - /data/v2ray/log:/var/log/v2ray
    command: run -config /etc/v2ray/config.json
    networks:
      - default_network
  bad_proxy:
    container_name: bad_proxy
    image: wwricu/bad-proxy-core:latest
    restart: always
    expose:
      - 8443
    volumes:
      - /data/bad_proxy/config.json:/etc/bad_proxy/config.json
    networks:
      - default_network
networks:
  default_network:
