name: Clean deploy
on:
  workflow_call:
    secrets:
      HOSTNAME:
        required: true
      ADMIN_HOSTNAME:
        required: true
      USERNAME:
        required: true
      PRIVATE_KEY:
        required: true
      V2RAY_UUID:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ADMIN_HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            mkdir /data
            mkdir /data/v2ray
            mkdir /data/bad_proxy
            rm -rf /data/deploy
            mkdir /data/deploy
      - uses: actions/checkout@v4
      - run: |
          echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
          echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
          echo HOSTNAME=${{ secrets.HOSTNAME }} >> .env
          echo ADMIN_HOSTNAME=${{ secrets.ADMIN_HOSTNAME }} >> .env
          sed -i "s/{V2RAY_UUID}/${{ secrets.V2RAY_UUID }}/g" v2ray/config.json
          sed -i "s/{TROJAN_UUID}/${{ secrets.V2RAY_UUID }}/g" bad_proxy/config.json
          sed -i "s/{BTP_UUID}/${{ secrets.V2RAY_UUID }}/g" bad_proxy/config.json
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ADMIN_HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "."
          target: "/data/deploy"
          overwrite: true
